#pragma once

#define TARGET_REAVER 0x1
#define TARGET_SWARMLING 0x2
#define TARGET_SPAWNLING 0x4
#define TARGET_GIANT 0x8
#define TARGET_ARMORED 0x10
#define TARGET_RUNNER 0x20
#define TARGET_MONSTER \
    (TARGET_REAVER | TARGET_SWARMLING | TARGET_SPAWNLING | TARGET_GIANT | TARGET_ARMORED | TARGET_RUNNER)

#define TARGET_APPARITION 0x100
#define TARGET_SPECTER 0x200
#define TARGET_SHADOW 0x400
#define TARGET_SPIRE 0x800
#define TARGET_GUARDIAN 0x1000
#define TARGET_SPECIAL \
    (TARGET_APPARITION | TARGET_SPECTER | TARGET_SHADOW | TARGET_SPIRE | TARGET_GUARDIAN)

// Do not try to search for structure in enemyController, nothing will be found
#define TARGET_STRUCTURE 0x80000

#define TARGET_ENEMY (TARGET_MONSTER | TARGET_SPECIAL)

#define TARGET_ALL (TARGET_ENEMY | TARGET_STRUCTURE)

enum TARGET_PRIORITY_TYPE
{
    PRIORITY_NEAREST = 0,
    PRIORITY_SWARMLINGS = 1,
    PRIORITY_GIANTS = 2,
    PRIORITY_RANDOM = 3,
    PRIORITY_STRUCTURE = 4,
    PRIORITY_SPECIAL = 5,
    PRIORITY_ARMOR = 6,
    PRIORITY_LEASTHP = 7,

    TARGET_PRIORITY_TYPE_COUNT
};

#ifdef DEBUG
static const char* TARGET_PRIORITY_TYPE_NAME[TARGET_PRIORITY_TYPE_COUNT] = {
    "Nearest to Orb",
    "Swarmlings",
    "Giants",
    "Random",
    "Structures",
    "Special",
    "Shielded/Armor",
    "Least HP",
};
#endif
